In [0]:
import numpy as np

Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.
Вычислите, по возможности не используя программирование: (5Е)**–1, где Е – единичная матрица размера 5х5.

обратная матица - 5**-1 * E (т.к. 5/5 = 1)




In [59]:
k = 2
l = 3
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.array([7, 8, 9])
print((k*l)*A)
print(k*(l*A))
print(k*A+k*B)
print(k*(A + B))
print((k+l)*A)
print(k*A + l*A)
print(np.dot(np.dot(A, B),C))
print(np.dot(np.dot(C, B),A))
print(np.dot((A+B),C))
print(np.dot(A, C) + np.dot(B, C))
print(np.dot(A, (B+C)))
print(np.dot(A, B)+ np.dot(A,C))

[ 6 12 18]
[ 6 12 18]
[10 14 18]
[10 14 18]
[ 5 10 15]
[ 5 10 15]
[224 256 288]
[122 244 366]
172
172
82
82


## $\det A = \left|
\begin{array}{cccc}
1 & 2 & 3\\
4 & 0 & 6\\
7 & 8 & 9
\end{array}
\right|=
1\left| 
\begin{array}{cccc}
0 & 6\\ 
8 & 9
\end{array} 
\right|
-2\left| 
\begin{array}{cccc}
4 & 6\\ 
7 & 9
\end{array} 
\right|
+3\left| 
\begin{array}{cccc}
4 & 0\\ 
7 & 8
\end{array} 
\right|=-48 + 12 + 96 = 60
$

In [70]:
print(0*9-8*6, 4*9-7*6, 4*8-0, '\n', 2*9-8*3, 1*9-3*7, 1*8-2*7, '\n', 2*6-0, 1*6-4*3, -4*2)

-48 -6 32 
 -6 -12 -6 
 12 -6 -8


In [71]:
A_m = np.array([[-48, 6, 32], [6, -12, 6], [12, 6, -8]]).T/60
print(A_m)
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
print(np.dot(A, A_m))

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]
[[ 1.00000000e+00 -2.77555756e-17  2.77555756e-17]
 [-2.22044605e-16  1.00000000e+00  5.55111512e-17]
 [-7.77156117e-16  2.77555756e-17  1.00000000e+00]]


In [78]:
D = np.array([[2, 2, 2, 2], [4, 4, 4, 4], [1, 1, 1, 1], [8, 8, 8, 8]])
print(D)
np.linalg.matrix_rank(D, 0.0001)

[[2 2 2 2]
 [4 4 4 4]
 [1 1 1 1]
 [8 8 8 8]]


1

Вычислите скалярное произведение двух векторов:  
(1, 5)  и  (2, 8)

2+5*8 = 42

In [83]:
a = np.array([1, 5])
b = np.array([2, 8])
np.inner(a, b)


42

Вычислите смешанное произведение трех векторов:
(1, 5, 0), (2, 8, 7) и (7, 1.5, 3) 


In [85]:
a = np.array([1, 5, 0], float)
b = np.array([2, 8, 7], float)
c = np.array([7, 1.5, 3], float)
v = np.cross(a, b)
print (np.inner(v, c))

228.5
